-- Danh mục 192 đơn vị tính được đối chiếu từ tài khoản iPOS ngày 2026-08-03.
-- An toàn khi chạy lại: cập nhật theo mã đơn vị tính.

alter table public.inventory_units
  add column if not exists description text;

insert into public.inventory_units (code, name, description, unit_type, decimal_places, is_active)
values
  ('0000008', 'KG', null, 'other', 3, true),
  ('0084', 'HỘP', null, 'other', 3, true),
  ('AM', 'Ấm', null, 'other', 3, true),
  ('AU', 'Âu', null, 'other', 3, true),
  ('BAG', 'BAG', null, 'other', 3, true),
  ('BAN', 'Bàn', 'Tiệc cưới', 'other', 3, true),
  ('BANG', 'Bảng', null, 'other', 3, true),
  ('BANH', 'BÁNH', null, 'other', 3, true),
  ('BAO', 'Bao', null, 'other', 3, true),
  ('BAO25', 'Bao 25', null, 'other', 3, true),
  ('BAP', 'Bắp', 'Bắp ngô...', 'other', 3, true),
  ('BAT', 'Bát', null, 'other', 3, true),
  ('BI', 'BÌ', null, 'other', 3, true),
  ('BIA', 'Bìa', 'Bìa đậu phụ...', 'other', 3, true),
  ('BICH', 'Bịch', null, 'other', 3, true),
  ('BINH', 'Bình', null, 'other', 3, true),
  ('BO', 'Bộ', null, 'other', 3, true),
  ('BO2', 'Bó', null, 'other', 3, true),
  ('BOC', 'Bọc', null, 'other', 3, true),
  ('BOHOA', 'Bó Hoa', null, 'other', 3, true),
  ('BOM', 'Bom', null, 'other', 3, true),
  ('BONG', 'Bông', 'Bông (Bông hoa)', 'other', 3, true),
  ('BOTTLE', 'Bottle', null, 'other', 3, true),
  ('BOWL', 'Bowl', null, 'other', 3, true),
  ('BOX', 'Box', null, 'other', 3, true),
  ('BUC', 'Bức', 'Khách bán tranh', 'other', 3, true),
  ('BUOI', 'Buổi', null, 'other', 3, true),
  ('CA', 'Ca', null, 'other', 3, true),
  ('CAI', 'Cái', null, 'other', 3, true),
  ('CAN', 'Can', null, 'other', 3, true),
  ('CANH', 'Cành', null, 'other', 3, true),
  ('CAP', 'Cặp', null, 'other', 3, true),
  ('CARAFE', 'Carafe', null, 'other', 3, true),
  ('CAY', 'Cây', null, 'other', 3, true),
  ('CHAI', 'Chai', null, 'other', 3, true),
  ('CHAO', 'Chảo', 'Dùng để làm đơn vị bánh mì chảo', 'other', 3, true),
  ('CHAU', 'Chậu', null, 'other', 3, true),
  ('CHEN', 'Chén', null, 'other', 3, true),
  ('CHI', 'Chỉ', 'Chỉ', 'other', 3, true),
  ('CHIEC', 'Chiếc', null, 'other', 3, true),
  ('CHUC', 'Chục', null, 'other', 3, true),
  ('CHUM', 'CHUM', null, 'other', 3, true),
  ('COC', 'Cốc', null, 'other', 3, true),
  ('COC1', 'Cọc', null, 'other', 3, true),
  ('COCKTAIL', 'Cocktail', null, 'other', 3, true),
  ('COMBO', 'Combo', null, 'other', 3, true),
  ('CON', 'Con', null, 'other', 3, true),
  ('COT', 'Cốt', null, 'other', 3, true),
  ('CUC', 'Cục', null, 'other', 3, true),
  ('CUON', 'Cuộn', null, 'other', 3, true),
  ('CUON01', 'Cuốn', 'Cuốn phim, album ...', 'other', 3, true),
  ('CUP', 'Cup', null, 'other', 3, true),
  ('DAN', 'Dàn', null, 'other', 3, true),
  ('DAY', 'Dây', null, 'other', 3, true),
  ('DE', 'Dẻ', 'Dẻ sườn bò, Dẻ sườn bò mỹ,...', 'other', 3, true),
  ('DEM', 'Đêm', null, 'other', 3, true),
  ('DIA', 'Đĩa', null, 'other', 3, true),
  ('DICHVU', 'Dịch Vụ', null, 'other', 3, true),
  ('DIEU', 'Điếu', null, 'other', 3, true),
  ('DISH', 'Dish', null, 'other', 3, true),
  ('DOAN', 'Đoàn', null, 'other', 3, true),
  ('DOI', 'Đôi', null, 'other', 3, true),
  ('DRAM', 'Dram', null, 'other', 3, true),
  ('EACH', 'Each', null, 'other', 3, true),
  ('GIO', 'Giờ', null, 'other', 3, true),
  ('GIOHANG', 'Giỏ Hàng', 'Giỏ, Giỏ hàng,...', 'other', 3, true),
  ('GIOT', 'Giọt', null, 'other', 3, true),
  ('GL', 'GL', null, 'other', 3, true),
  ('GLASS', 'Glass', null, 'other', 3, true),
  ('GOI', 'Gói', null, 'other', 3, true),
  ('GOI1KG', 'Gói 1 Kg', null, 'other', 3, true),
  ('GR', 'Gram', null, 'other', 3, true),
  ('GUEST', 'GUEST', null, 'other', 3, true),
  ('HAT', 'HẠT', null, 'other', 3, true),
  ('HOP', 'Hộp', null, 'other', 3, true),
  ('HOP16', 'Hộp 16', null, 'other', 3, true),
  ('HOP24', 'Hộp 24', null, 'other', 3, true),
  ('HU', 'Hũ', null, 'other', 3, true),
  ('JAR', 'JAR', null, 'other', 3, true),
  ('JUG', 'Jug', null, 'other', 3, true),
  ('KE', 'Kệ', null, 'other', 3, true),
  ('KEG', 'Keg', null, 'other', 3, true),
  ('KENG', 'Keng', null, 'other', 3, true),
  ('KET', 'Két', null, 'other', 3, true),
  ('KG', 'Kg', null, 'other', 3, true),
  ('KGCOT', 'Kg (Cốt)', null, 'other', 3, true),
  ('KHACH', 'Khách', null, 'other', 3, true),
  ('KHAY', 'Khay', null, 'other', 3, true),
  ('KHUC', 'Khúc', null, 'other', 3, true),
  ('KIEN', 'Kiện', null, 'other', 3, true),
  ('KWH', 'Kwh', null, 'other', 3, true),
  ('LA', 'Lá', 'Lá rong biển, lá vàng', 'other', 3, true),
  ('LAN', 'Lần', null, 'other', 3, true),
  ('LANG', 'Lạng', null, 'other', 3, true),
  ('LANGHOA', 'Lẵng', null, 'other', 3, true),
  ('LIT', 'Lít', null, 'other', 3, true),
  ('LO', 'Lọ', null, 'other', 3, true),
  ('LOAF', 'Loaf', 'LOAF', 'other', 3, true),
  ('LOC', 'Lốc', 'Lốc', 'other', 3, true),
  ('LON', 'Lon', null, 'other', 3, true),
  ('LONG', 'Lồng', null, 'other', 3, true),
  ('LUONG', 'Lượng', null, 'other', 3, true),
  ('LUOT', 'Lượt', null, 'other', 3, true),
  ('LY', 'Ly', null, 'other', 3, true),
  ('M', 'Mét', null, 'other', 3, true),
  ('M2', 'M2', null, 'other', 3, true),
  ('MAM', 'Mâm', null, 'other', 3, true),
  ('MAU', 'Mẫu', null, 'other', 3, true),
  ('ME', 'Mẻ', null, 'other', 3, true),
  ('MET', 'Mẹt', null, 'other', 3, true),
  ('METKHOI', 'Mét Khối', null, 'other', 3, true),
  ('MG', 'Miligam', null, 'other', 3, true),
  ('MIENG', 'Miếng', null, 'other', 3, true),
  ('ML', 'ML', 'Mililit', 'other', 3, true),
  ('MO', 'Mớ', null, 'other', 3, true),
  ('MON', 'Món', null, 'other', 3, true),
  ('MUG', 'Mug', 'Cốc', 'other', 3, true),
  ('MUI', 'MÚI', null, 'other', 3, true),
  ('MUONG', 'Muỗng', null, 'other', 3, true),
  ('NAI', 'Nải', 'Nải', 'other', 3, true),
  ('NAM', 'Nậm', null, 'other', 3, true),
  ('NGAY', 'Ngày', null, 'other', 3, true),
  ('NGUOI', 'Người', null, 'other', 3, true),
  ('NHANH', 'NHÁNH', null, 'other', 3, true),
  ('NIEU', 'Niêu', null, 'other', 3, true),
  ('NIGHT', 'Night', null, 'other', 3, true),
  ('NOI', 'Nồi', null, 'other', 3, true),
  ('O', 'Ổ', null, 'other', 3, true),
  ('ONG', 'Ống', 'Ống hút', 'other', 3, true),
  ('PACK', 'Pack', null, 'other', 3, true),
  ('PART', 'Part', null, 'other', 3, true),
  ('PAX', 'Pax', null, 'other', 3, true),
  ('PCS', 'PCS', 'PCS', 'other', 3, true),
  ('PERSON', 'Person', null, 'other', 3, true),
  ('PHAN', 'Phần', null, 'other', 3, true),
  ('PHIN', 'Phin', null, 'other', 3, true),
  ('PHONG2', 'Phòng', 'Phòng khách hàng, phòng nghỉ', 'other', 3, true),
  ('PHUT', 'Phút', null, 'other', 3, true),
  ('PIECE', 'Piece', null, 'other', 3, true),
  ('PLATE', 'Plate', null, 'other', 3, true),
  ('PORTION', 'Portion', null, 'other', 3, true),
  ('POT', 'Pot', null, 'other', 3, true),
  ('QUA', 'Quả', null, 'other', 3, true),
  ('QUE', 'Que', null, 'other', 3, true),
  ('QUY', 'Quý', null, 'other', 3, true),
  ('QUYEN', 'Quyển', null, 'other', 3, true),
  ('RAM', 'Ram', null, 'other', 3, true),
  ('RO', 'Rổ', null, 'other', 3, true),
  ('ROLL', 'Roll', null, 'other', 3, true),
  ('SERVE', 'Serve', null, 'other', 3, true),
  ('SERVING', 'Serving', null, 'other', 3, true),
  ('SET', 'Set', null, 'other', 3, true),
  ('SHOT', 'Shot', null, 'other', 3, true),
  ('SHOW', 'Show', null, 'other', 3, true),
  ('SO', 'Số', null, 'other', 3, true),
  ('SOI', 'Sợi', null, 'other', 3, true),
  ('SUAT', 'Suất', null, 'other', 3, true),
  ('T', 'TỜ', 'TỜ GIẤY GÓI BÁNH MÌ', 'other', 3, true),
  ('TA', 'Tá', null, 'other', 3, true),
  ('TAG', 'Tag', null, 'other', 3, true),
  ('TAM', 'Tấm', null, 'other', 3, true),
  ('TAP', 'Tập', null, 'other', 3, true),
  ('TEP', 'Tép', null, 'other', 3, true),
  ('THANG', 'Tháng', null, 'other', 3, true),
  ('THANH', 'Thanh', null, 'other', 3, true),
  ('THAP', 'Tháp', null, 'other', 3, true),
  ('THE', 'Thẻ', null, 'other', 3, true),
  ('THEP', 'Thếp', null, 'other', 3, true),
  ('THO', 'Thố', 'Thố đựng cơm', 'other', 3, true),
  ('THUNG', 'Thùng', null, 'other', 3, true),
  ('TIEC', 'Tiệc', 'Tiệc', 'other', 3, true),
  ('TIN', 'TIN', null, 'other', 3, true),
  ('TO', 'Tô', null, 'other', 3, true),
  ('TRAI', 'Trái', null, 'other', 3, true),
  ('TRAY', 'Tray', null, 'other', 3, true),
  ('TUI', 'Túi', null, 'other', 3, true),
  ('TUI500', 'Túi 500G', null, 'other', 3, true),
  ('TUYP', 'Tuýp', null, 'other', 3, true),
  ('VA', 'VÁ', null, 'other', 3, true),
  ('VAI', 'VẠI', null, 'other', 3, true),
  ('VE', 'Vé', 'Vé Buffet', 'other', 3, true),
  ('VI', 'Vỉ', null, 'other', 3, true),
  ('VIEN', 'Viên', null, 'other', 3, true),
  ('VND', 'Vnđ', null, 'other', 3, true),
  ('VONG', 'Vòng', null, 'other', 3, true),
  ('XACH', 'XÁCH', null, 'other', 3, true),
  ('XAP', 'Xấp', null, 'other', 3, true),
  ('XI', 'Xị', null, 'other', 3, true),
  ('XIEN', 'Xiên', null, 'other', 3, true),
  ('XO', 'Xô', null, 'other', 3, true),
  ('XUAT', 'Xuất', null, 'other', 3, true),
  ('XUNG', 'Xửng', null, 'other', 3, true)
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  is_active = excluded.is_active,
  updated_at = now();

notify pgrst, 'reload schema';

