-- Nhật ký IPN MoMo cho thanh toán QR Order tại quầy.
-- Có thể chạy lại an toàn trong Supabase SQL Editor.

begin;

create table if not exists public.momo_webhook_logs (
  id bigint generated by default as identity primary key,
  momo_order_id text not null default '',
  request_id text not null default '',
  transaction_id text,
  result_code integer not null default -1,
  amount numeric(14, 0) not null default 0,
  payment_option text not null default '',
  raw_payload jsonb not null default '{}'::jsonb,
  matched_payment_session_id uuid,
  matched_order_id text,
  processed_result text not null default '',
  created_at timestamptz not null default now(),
  constraint momo_webhook_logs_amount_non_negative check (amount >= 0),
  constraint momo_webhook_logs_raw_payload_object check (jsonb_typeof(raw_payload) = 'object')
);

create index if not exists momo_webhook_logs_created_at_idx
  on public.momo_webhook_logs (created_at desc);
create index if not exists momo_webhook_logs_order_id_idx
  on public.momo_webhook_logs (momo_order_id)
  where btrim(momo_order_id) <> '';
create index if not exists momo_webhook_logs_transaction_id_idx
  on public.momo_webhook_logs (transaction_id)
  where transaction_id is not null and btrim(transaction_id) <> '';
create index if not exists momo_webhook_logs_session_idx
  on public.momo_webhook_logs (matched_payment_session_id)
  where matched_payment_session_id is not null;

alter table public.momo_webhook_logs enable row level security;
revoke all on table public.momo_webhook_logs from anon;
revoke all on table public.momo_webhook_logs from authenticated;
grant select, insert, update, delete on table public.momo_webhook_logs to service_role;
grant select on table public.momo_webhook_logs to authenticated;
grant usage, select on sequence public.momo_webhook_logs_id_seq to service_role;

drop policy if exists momo_webhook_logs_admin_read on public.momo_webhook_logs;
create policy momo_webhook_logs_admin_read
on public.momo_webhook_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.auth_user_id = (select auth.uid())
      and lower(coalesce(p.status, '')) = 'active'
      and lower(coalesce(p.role, '')) = 'admin'
  )
);

commit;
