import AdminDashboardSection from "../dashboard/AdminDashboardSection.jsx";

export default function AdminDashboardPage({
  dashboardSearch,
  setDashboardSearch,
  dashboardDateFrom,
  setDashboardDateFrom,
  dashboardDateTo,
  setDashboardDateTo,
  dashboardDatePreset,
  setDashboardDatePreset,
  dashboardChartPreset,
  setDashboardChartPreset,
  openBranches,
  totalBranches,
  ordersTotal,
  ordersNew,
  ordersDoing,
  todayRevenue,
  totalCustomers,
  activeProducts,
  toppingsCount,
  dashboardQuickActions,
  openAdminNav,
  flatAdminNav,
  filteredRecentOrders,
  ordersSnapshot,
  chartOrdersSnapshot
}) {
  return (
    <AdminDashboardSection
      dashboardSearch={dashboardSearch}
      setDashboardSearch={setDashboardSearch}
      dashboardDateFrom={dashboardDateFrom}
      setDashboardDateFrom={setDashboardDateFrom}
      dashboardDateTo={dashboardDateTo}
      setDashboardDateTo={setDashboardDateTo}
      dashboardDatePreset={dashboardDatePreset}
      setDashboardDatePreset={setDashboardDatePreset}
      dashboardChartPreset={dashboardChartPreset}
      setDashboardChartPreset={setDashboardChartPreset}
      openBranches={openBranches}
      totalBranches={totalBranches}
      ordersTotal={ordersTotal}
      ordersNew={ordersNew}
      ordersDoing={ordersDoing}
      todayRevenue={todayRevenue}
      totalCustomers={totalCustomers}
      activeProducts={activeProducts}
      toppingsCount={toppingsCount}
      dashboardQuickActions={dashboardQuickActions}
      openAdminNav={openAdminNav}
      flatAdminNav={flatAdminNav}
      filteredRecentOrders={filteredRecentOrders}
      ordersSnapshot={ordersSnapshot}
      chartOrdersSnapshot={chartOrdersSnapshot}
    />
  );
}
