import CustomerShell from "../customer/product/CustomerShell.jsx";
import { createOrderActions } from "../orders/orderActions.js";
import { createCustomerPageProps } from "./customerPageProps.js";
import { createCustomerShellProps } from "./customerShellProps.js";
import { rewardFeatureFlags } from "../../constants/featureFlags.js";
import {
  selectCheckoutCoupons,
  selectCheckoutSmartPromotions,
  selectHomeCoupons,
  selectHomeSmartPromotions
} from "../../services/promotionSelectors.js";

function getCustomerSalesChannel(checkoutPreset = {}) {
  const sourceText = String(
    checkoutPreset?.orderSource ||
      checkoutPreset?.source ||
      (typeof window !== "undefined" ? window.location.pathname : "")
  ).toLowerCase();
  return sourceText.includes("qr") ? "qr" : "web";
}

export default function CustomerAppShell({
  cart,
  userProfile,
  currentPhone,
  setDemoOrdersState,
  loyaltyByPhoneStorage,
  setDemoLoyaltyState,
  addressStorage,
  updateAddress,
  addAddress,
  setDefaultAddress,
  setDemoAddressesState,
  setUserProfile,
  getMemberRank,
  setCurrentOrder,
  setOrderStatus,
  setCart,
  repriceCartNow,
  saveDemoOrders,
  demoOrders,
  navigate,
  activeCategory,
  setActiveCategory,
  customerCategories,
  filteredProducts,
  customerProducts,
  storeToppings,
  customerPromoCards,
  adminCoupons,
  smartPromotions,
  homeContent,
  openProduct,
  addToCart,
  openOptionModal,
  selectedProduct,
  selectedSpice,
  setSelectedSpice,
  selectedToppings,
  setSelectedToppings,
  note,
  setNote,
  quantity,
  setQuantity,
  composedUserProfile,
  activeDemoUser,
  saveDemoUser,
  loginOrRegisterByPhone,
  isRegisteredCustomer,
  hasCustomerAuthSession,
  requiresCustomerAuthSession,
  logoutDemoUser,
  demoAddresses,
  saveDemoAddresses,
  profileLoyalty,
  saveDemoLoyalty,
  profileOrders,
  isSessionRestoring,
  isSessionBootstrapping,
  orderStatus,
  subtotal,
  ship,
  total,
  effectiveDeliveryZones,
  branches,
  checkoutPreset,
  setCheckoutPreset,
  hasRegisteredAccountByPhone,
  serviceNotice,
  setServiceNotice,
  getStoreBlockNotice,
  isBranchOpenNow,
  buildStoreOfflineNotice,
  buildDeliveryDisabledNotice,
  buildPickupDisabledNotice,
  buildOutOfHoursNotice,
  page,
  Home,
  Menu,
  ProductDetailModal,
  CheckoutContainer,
  Checkout,
  Success,
  TrackingContainer,
  Tracking,
  Loyalty,
  AccountContainer,
  Account,
  activeTab,
  handleBottomNav,
  openOptionModalFromHome,
  openCartItemEditor,
  currentOrder,
  confirmCurrentOrder,
  reorderOrder,
  optionModalText,
  spiceLevels,
  normalizeOrderOption,
  closeOnlyOnBackdrop,
  OptionGroup,
  isOptionModalOpen,
  closeOptionModal,
  editingCartId,
  cartCount,
  formatMoney,
  toastVisible
}) {
  const {
    createOrderFromCheckout,
    confirmCurrentOrder: confirmCurrentOrderAction
  } = createOrderActions({
    cart,
    userProfile,
    currentPhone,
    setDemoOrdersState,
    loyaltyByPhoneStorage,
    setDemoLoyaltyState,
    addressStorage,
    updateAddress,
    addAddress,
    setDefaultAddress,
    setDemoAddressesState,
    setUserProfile,
    getMemberRank,
    setCurrentOrder,
    setOrderStatus,
    setCart,
    saveDemoOrders,
    demoOrders,
    currentOrder,
    saveDemoUser
  });

  const effectiveSmartPromotions = rewardFeatureFlags.enableMilestoneReward ? smartPromotions : [];
  const customerSalesChannel = getCustomerSalesChannel(checkoutPreset);
  const homeCoupons = selectHomeCoupons(adminCoupons, "web");
  const checkoutCoupons = selectCheckoutCoupons(adminCoupons, customerSalesChannel);
  const homeSmartPromotions = selectHomeSmartPromotions(effectiveSmartPromotions, "web");
  const checkoutSmartPromotions = selectCheckoutSmartPromotions(effectiveSmartPromotions, customerSalesChannel);

  const pageProps = createCustomerPageProps({
    navigate,
    activeCategory,
    setActiveCategory,
    customerCategories,
    filteredProducts,
    storeProducts: customerProducts,
    storeToppings,
    customerPromoCards,
    adminCoupons,
    effectiveSmartPromotions,
    homeContent,
    openProduct,
    addToCart,
    openOptionModal,
    selectedProduct,
    selectedSpice,
    setSelectedSpice,
    selectedToppings,
    setSelectedToppings,
    note,
    setNote,
    quantity,
    setQuantity,
    cart,
    setCart,
    composedUserProfile,
    activeDemoUser,
    saveDemoUser,
    currentPhone,
    loginOrRegisterByPhone,
    isRegisteredCustomer,
    hasCustomerAuthSession,
    requiresCustomerAuthSession,
    logoutDemoUser,
    demoAddresses,
    saveDemoAddresses,
    profileLoyalty,
    saveDemoLoyalty,
    setDemoLoyaltyState,
    profileOrders,
    saveDemoOrders,
    isSessionRestoring,
    isSessionBootstrapping,
    orderStatus,
    setOrderStatus,
    createOrderFromCheckout,
    repriceCartNow,
    subtotal,
    ship,
    total,
    effectiveDeliveryZones,
    branches,
    checkoutPreset,
    setCheckoutPreset,
    hasRegisteredAccountByPhone,
    serviceNotice,
    setServiceNotice,
    getStoreBlockNotice,
    isBranchOpenNow,
    buildStoreOfflineNotice,
    buildDeliveryDisabledNotice,
    buildPickupDisabledNotice,
    buildOutOfHoursNotice,
    homeCoupons,
    checkoutCoupons,
    homeSmartPromotions,
    checkoutSmartPromotions
  });

  const customerShellProps = createCustomerShellProps({
    page,
    pageProps,
    Home,
    Menu,
    ProductDetailModal,
    CheckoutContainer,
    Checkout,
    Success,
    TrackingContainer,
    Tracking,
    Loyalty,
    AccountContainer,
    Account,
    activeTab,
    handleBottomNav,
    openOptionModalFromHome,
    openCartItemEditor,
    currentOrder,
    branches,
    orderStatus,
    confirmCurrentOrder: confirmCurrentOrder || confirmCurrentOrderAction,
    composedUserProfile,
    currentPhone,
    reorderOrder,
    setUserProfile,
    profileLoyalty,
    saveDemoLoyalty,
    subtotal,
    isRegisteredCustomer,
    hasCustomerAuthSession,
    requiresCustomerAuthSession,
    activeDemoUser,
    saveDemoUser,
    loginOrRegisterByPhone,
    logoutDemoUser,
    demoAddresses,
    saveDemoAddresses,
    profileOrders,
    isOptionModalOpen,
    selectedProduct,
    selectedSpice,
    setSelectedSpice,
    selectedToppings,
    setSelectedToppings,
    storeToppings,
    note,
    setNote,
    quantity,
    setQuantity,
    closeOptionModal,
    optionModalText,
    spiceLevels,
    normalizeOrderOption,
    closeOnlyOnBackdrop,
    OptionGroup,
    editingCartId,
    addToCart,
    cartCount,
    navigate,
    formatMoney,
    toastVisible,
    serviceNotice,
    setServiceNotice,
    getStoreBlockNotice
  });

  return <CustomerShell {...customerShellProps} />;
}
