export function createCustomerPageProps({
  navigate,
  activeCategory,
  setActiveCategory,
  customerCategories,
  filteredProducts,
  storeProducts,
  storeToppings,
  customerPromoCards,
  adminCoupons,
  effectiveSmartPromotions,
  homeContent,
  openProduct,
  addToCart,
  openOptionModal,
  selectedProduct,
  selectedSpice,
  setSelectedSpice,
  selectedToppings,
  setSelectedToppings,
  note,
  setNote,
  quantity,
  setQuantity,
  cart,
  setCart,
  composedUserProfile,
  activeDemoUser,
  saveDemoUser,
  currentPhone,
  loginOrRegisterByPhone,
  isRegisteredCustomer,
  hasCustomerAuthSession,
  requiresCustomerAuthSession,
  logoutDemoUser,
  demoAddresses,
  saveDemoAddresses,
  profileLoyalty,
  saveDemoLoyalty,
  setDemoLoyaltyState,
  profileOrders,
  saveDemoOrders,
  isSessionRestoring,
  isSessionBootstrapping,
  orderStatus,
  setOrderStatus,
  createOrderFromCheckout,
  repriceCartNow,
  subtotal,
  ship,
  total,
  effectiveDeliveryZones,
  branches,
  checkoutPreset,
  setCheckoutPreset,
  hasRegisteredAccountByPhone,
  serviceNotice,
  setServiceNotice,
  getStoreBlockNotice,
  isBranchOpenNow,
  buildStoreOfflineNotice,
  buildDeliveryDisabledNotice,
  buildPickupDisabledNotice,
  buildOutOfHoursNotice,
  homeCoupons,
  checkoutCoupons,
  homeSmartPromotions,
  checkoutSmartPromotions
}) {
  return {
    navigate,
    activeCategory,
    setActiveCategory,
    categories: customerCategories,
    filteredProducts,
    products: storeProducts,
    toppings: storeToppings,
    promos: customerPromoCards,
    coupons: adminCoupons,
    smartPromotions: effectiveSmartPromotions,
    homeCoupons: homeCoupons || adminCoupons,
    checkoutCoupons: checkoutCoupons || adminCoupons,
    homeSmartPromotions: homeSmartPromotions || effectiveSmartPromotions,
    checkoutSmartPromotions: checkoutSmartPromotions || effectiveSmartPromotions,
    homeContent,
    openProduct,
    addToCart,
    openOptionModal,
    selectedProduct,
    selectedSpice,
    setSelectedSpice,
    selectedToppings,
    setSelectedToppings,
    note,
    setNote,
    quantity,
    setQuantity,
    cart,
    setCart,
    userProfile: composedUserProfile,
    demoUser: activeDemoUser,
    setDemoUser: saveDemoUser,
    currentPhone,
    loginOrRegisterByPhone,
    isRegisteredCustomer,
    hasCustomerAuthSession,
    requiresCustomerAuthSession,
    logoutDemoUser,
    demoAddresses,
    setDemoAddresses: saveDemoAddresses,
    demoLoyalty: profileLoyalty,
    setDemoLoyalty: saveDemoLoyalty,
    setDemoLoyaltyState,
    demoOrders: profileOrders,
    setDemoOrders: saveDemoOrders,
    isSessionRestoring,
    isSessionBootstrapping,
    orderStatus,
    setOrderStatus,
    createOrderFromCheckout,
    repriceCartNow,
    subtotal,
    ship,
    total,
    deliveryZones: effectiveDeliveryZones,
    branches,
    checkoutPreset,
    setCheckoutPreset,
    hasRegisteredAccountByPhone,
    serviceNotice,
    setServiceNotice,
    getStoreBlockNotice,
    isBranchOpenNow,
    buildStoreOfflineNotice,
    buildDeliveryDisabledNotice,
    buildPickupDisabledNotice,
    buildOutOfHoursNotice
  };
}
