export function createCustomerShellProps({
  page,
  pageProps,
  Home,
  Menu,
  ProductDetailModal,
  CheckoutContainer,
  Checkout,
  Success,
  TrackingContainer,
  Tracking,
  Loyalty,
  AccountContainer,
  Account,
  activeTab,
  handleBottomNav,
  openOptionModalFromHome,
  openCartItemEditor,
  currentOrder,
  branches,
  orderStatus,
  confirmCurrentOrder,
  composedUserProfile,
  currentPhone,
  reorderOrder,
  setUserProfile,
  profileLoyalty,
  saveDemoLoyalty,
  subtotal,
  isRegisteredCustomer,
  activeDemoUser,
  saveDemoUser,
  loginOrRegisterByPhone,
  logoutDemoUser,
  demoAddresses,
  saveDemoAddresses,
  profileOrders,
  isOptionModalOpen,
  selectedProduct,
  selectedSpice,
  setSelectedSpice,
  selectedToppings,
  setSelectedToppings,
  storeToppings,
  note,
  setNote,
  quantity,
  setQuantity,
  closeOptionModal,
  optionModalText,
  spiceLevels,
  normalizeOrderOption,
  closeOnlyOnBackdrop,
  OptionGroup,
  editingCartId,
  addToCart,
  cartCount,
  navigate,
  formatMoney,
  toastVisible,
  serviceNotice,
  setServiceNotice,
  getStoreBlockNotice
}) {
  return {
    page: page,
    pageProps: {
      ...pageProps,
      Home,
      Menu,
      Detail: ProductDetailModal,
      Checkout: CheckoutContainer,
      checkoutRender: Checkout,
      Success,
      Tracking: TrackingContainer,
      trackingRender: Tracking,
      Loyalty,
      Account: AccountContainer,
      accountRender: Account
    },
    activeTab: activeTab,
    handleBottomNav: handleBottomNav,
    openOptionModalFromHome: openOptionModalFromHome,
    openCartItemEditor: openCartItemEditor,
    currentOrder: currentOrder,
    branches: branches,
    orderStatus: orderStatus,
    confirmCurrentOrder: confirmCurrentOrder,
    composedUserProfile: composedUserProfile,
    currentPhone: currentPhone,
    reorderOrder: reorderOrder,
    setUserProfile: setUserProfile,
    profileLoyalty: profileLoyalty,
    saveDemoLoyalty: saveDemoLoyalty,
    subtotal: subtotal,
    isRegisteredCustomer: isRegisteredCustomer,
    activeDemoUser: activeDemoUser,
    saveDemoUser: saveDemoUser,
    loginOrRegisterByPhone: loginOrRegisterByPhone,
    logoutDemoUser: logoutDemoUser,
    demoAddresses: demoAddresses,
    saveDemoAddresses: saveDemoAddresses,
    profileOrders: profileOrders,
    isOptionModalOpen: isOptionModalOpen,
    selectedProduct: selectedProduct,
    selectedSpice: selectedSpice,
    setSelectedSpice: setSelectedSpice,
    selectedToppings: selectedToppings,
    setSelectedToppings: setSelectedToppings,
    storeToppings: storeToppings,
    note: note,
    setNote: setNote,
    quantity: quantity,
    setQuantity: setQuantity,
    closeOptionModal: closeOptionModal,
    optionModalText: optionModalText,
    spiceLevels: spiceLevels,
    normalizeOrderOption: normalizeOrderOption,
    closeOnlyOnBackdrop: closeOnlyOnBackdrop,
    OptionGroup: OptionGroup,
    editingCartId: editingCartId,
    addToCart: addToCart,
    cartCount: cartCount,
    navigate: navigate,
    formatMoney: formatMoney,
    toastVisible: toastVisible,
    serviceNotice: serviceNotice,
    setServiceNotice: setServiceNotice,
    getStoreBlockNotice: getStoreBlockNotice
  };
}
