-- Loyalty V2 - Phase 2 database foundation
-- Additive migration: giữ nguyên RPC và quyền legacy để không làm gián đoạn runtime hiện tại.

begin;

create extension if not exists pgcrypto;

create schema if not exists loyalty_private;
revoke all on schema loyalty_private from public, anon;

create table if not exists public.loyalty_rule_versions (
  id uuid primary key default gen_random_uuid(),
  version_number bigint generated by default as identity,
  status text not null default 'DRAFT',
  effective_from timestamptz not null default now(),
  earn_numerator bigint not null,
  earn_denominator bigint not null,
  redeem_point_unit bigint not null default 1,
  redeem_value bigint not null default 1,
  checkin_daily_points integer not null default 0,
  streak_rewards jsonb not null default '{}'::jsonb,
  source_config jsonb not null default '{}'::jsonb,
  created_by uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  retired_at timestamptz null,
  constraint loyalty_rule_versions_version_number_key unique (version_number),
  constraint loyalty_rule_versions_status_check
    check (status in ('DRAFT', 'ACTIVE', 'RETIRED')),
  constraint loyalty_rule_versions_earn_check
    check (earn_numerator > 0 and earn_denominator > 0),
  constraint loyalty_rule_versions_redeem_check
    check (redeem_point_unit > 0 and redeem_value > 0),
  constraint loyalty_rule_versions_checkin_check
    check (checkin_daily_points >= 0)
);

create unique index if not exists loyalty_rule_versions_one_active_idx
on public.loyalty_rule_versions ((status))
where status = 'ACTIVE';

create index if not exists loyalty_rule_versions_effective_idx
on public.loyalty_rule_versions (effective_from desc, version_number desc);

alter table public.loyalty_rule_versions enable row level security;

drop policy if exists loyalty_rule_versions_read_active on public.loyalty_rule_versions;
create policy loyalty_rule_versions_read_active
on public.loyalty_rule_versions
for select
to anon, authenticated
using (status = 'ACTIVE');

grant select on public.loyalty_rule_versions to anon, authenticated;
revoke insert, update, delete on public.loyalty_rule_versions from public, anon, authenticated;

-- Tạo phiên bản V1 từ ghr_loyalty hiện hành. Chỉ chạy khi chưa có rule nào.
insert into public.loyalty_rule_versions (
  status,
  effective_from,
  earn_numerator,
  earn_denominator,
  redeem_point_unit,
  redeem_value,
  checkin_daily_points,
  streak_rewards,
  source_config
)
select
  'ACTIVE',
  now(),
  greatest(coalesce((c.value ->> 'pointPerUnit')::bigint, 1), 1),
  greatest(coalesce((c.value ->> 'currencyPerPoint')::bigint, 100), 1),
  greatest(coalesce((c.value ->> 'redeemPointUnit')::bigint, 1), 1),
  greatest(coalesce((c.value ->> 'redeemValue')::bigint, 1), 1),
  greatest(coalesce((c.value ->> 'checkinDailyPoints')::integer, 0), 0),
  coalesce(c.value -> 'streakRewards', '{}'::jsonb),
  coalesce(c.value, '{}'::jsonb) || jsonb_build_object(
    'migration', 'loyalty_v2_phase_2',
    'legacyConfigId', 'ghr_loyalty'
  )
from public.app_configs c
where c.id = 'ghr_loyalty'
  and not exists (select 1 from public.loyalty_rule_versions)
on conflict do nothing;

-- Fallback nếu production chưa có ghr_loyalty.
insert into public.loyalty_rule_versions (
  status,
  earn_numerator,
  earn_denominator,
  redeem_point_unit,
  redeem_value,
  checkin_daily_points,
  streak_rewards,
  source_config
)
select
  'ACTIVE', 1, 100, 1, 1, 0, '{}'::jsonb,
  jsonb_build_object('migration', 'loyalty_v2_phase_2', 'fallback', true)
where not exists (select 1 from public.loyalty_rule_versions)
on conflict do nothing;

-- Snapshot loyalty trên mọi nguồn đơn.
alter table public.orders
  add column if not exists loyalty_rule_version_id uuid null,
  add column if not exists points_base_amount numeric null,
  add column if not exists expected_earn_points integer null,
  add column if not exists points_spent integer null,
  add column if not exists points_discount_amount numeric null;

alter table public.partner_orders
  add column if not exists loyalty_rule_version_id uuid null,
  add column if not exists expected_earn_points integer null,
  add column if not exists points_spent integer null,
  add column if not exists points_discount_amount numeric null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'orders_loyalty_rule_version_fk'
      and conrelid = 'public.orders'::regclass
  ) then
    alter table public.orders
      add constraint orders_loyalty_rule_version_fk
      foreign key (loyalty_rule_version_id)
      references public.loyalty_rule_versions(id)
      on delete restrict
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'partner_orders_loyalty_rule_version_fk'
      and conrelid = 'public.partner_orders'::regclass
  ) then
    alter table public.partner_orders
      add constraint partner_orders_loyalty_rule_version_fk
      foreign key (loyalty_rule_version_id)
      references public.loyalty_rule_versions(id)
      on delete restrict
      not valid;
  end if;
end;
$$;

-- Mở rộng ledger. Các cột legacy được giữ nguyên để frontend cũ tiếp tục đọc.
alter table public.loyalty_ledger
  add column if not exists source_type text null,
  add column if not exists source_order_id text null,
  add column if not exists action text null,
  add column if not exists action_version smallint null,
  add column if not exists idempotency_key text null,
  add column if not exists rule_version_id uuid null,
  add column if not exists reversal_of_ledger_id text null,
  add column if not exists actor_type text null,
  add column if not exists actor_id uuid null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'loyalty_ledger_rule_version_fk'
      and conrelid = 'public.loyalty_ledger'::regclass
  ) then
    alter table public.loyalty_ledger
      add constraint loyalty_ledger_rule_version_fk
      foreign key (rule_version_id)
      references public.loyalty_rule_versions(id)
      on delete restrict
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'loyalty_ledger_reversal_fk'
      and conrelid = 'public.loyalty_ledger'::regclass
  ) then
    alter table public.loyalty_ledger
      add constraint loyalty_ledger_reversal_fk
      foreign key (reversal_of_ledger_id)
      references public.loyalty_ledger(id)
      on delete restrict
      not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'loyalty_ledger_v2_source_check'
      and conrelid = 'public.loyalty_ledger'::regclass
  ) then
    alter table public.loyalty_ledger
      add constraint loyalty_ledger_v2_source_check
      check (
        source_type is null
        or source_type in ('ORDER', 'PARTNER_ORDER', 'CUSTOMER_DAY', 'CUSTOMER_STREAK', 'ADMIN')
      ) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'loyalty_ledger_v2_action_check'
      and conrelid = 'public.loyalty_ledger'::regclass
  ) then
    alter table public.loyalty_ledger
      add constraint loyalty_ledger_v2_action_check
      check (
        action is null
        or action in (
          'SPEND', 'SETTLE_EARN', 'REVERSE_SPEND', 'REVERSE_EARN',
          'CLAIM_PARTNER_EARN', 'CHECKIN', 'MILESTONE', 'ADMIN_ADJUST'
        )
      ) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'loyalty_ledger_v2_identity_check'
      and conrelid = 'public.loyalty_ledger'::regclass
  ) then
    alter table public.loyalty_ledger
      add constraint loyalty_ledger_v2_identity_check
      check (
        action is null
        or (
          source_type is not null
          and nullif(trim(source_order_id), '') is not null
          and action_version is not null
          and action_version > 0
          and nullif(trim(idempotency_key), '') is not null
        )
      ) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'loyalty_ledger_v2_sign_check'
      and conrelid = 'public.loyalty_ledger'::regclass
  ) then
    alter table public.loyalty_ledger
      add constraint loyalty_ledger_v2_sign_check
      check (
        action is null
        or (action in ('SETTLE_EARN', 'REVERSE_SPEND', 'CLAIM_PARTNER_EARN', 'CHECKIN', 'MILESTONE') and points > 0)
        or (action in ('SPEND', 'REVERSE_EARN') and points < 0)
        or (action = 'ADMIN_ADJUST' and points <> 0)
      ) not valid;
  end if;
end;
$$;

create unique index if not exists loyalty_ledger_v2_business_event_unique
on public.loyalty_ledger (source_type, source_order_id, action, action_version)
where source_type is not null and source_order_id is not null and action is not null;

create unique index if not exists loyalty_ledger_v2_idempotency_unique
on public.loyalty_ledger (idempotency_key)
where idempotency_key is not null;

create unique index if not exists loyalty_ledger_v2_reversal_unique
on public.loyalty_ledger (reversal_of_ledger_id, action)
where reversal_of_ledger_id is not null;

create index if not exists loyalty_ledger_v2_rule_version_idx
on public.loyalty_ledger (rule_version_id)
where rule_version_id is not null;

create index if not exists orders_loyalty_rule_version_idx
on public.orders (loyalty_rule_version_id)
where loyalty_rule_version_id is not null;

create index if not exists partner_orders_loyalty_rule_version_idx
on public.partner_orders (loyalty_rule_version_id)
where loyalty_rule_version_id is not null;

-- Số dư phải luôn bằng tổng ledger. REVERSE_EARN có thể tạo số dư âm (nợ điểm)
-- nếu khách đã tiêu điểm trước khi đơn bị hoàn/hủy.
create or replace function public.recompute_loyalty_account(p_phone text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_phone text := btrim(coalesce(p_phone, ''));
  v_total integer := 0;
begin
  if v_phone = '' then
    return;
  end if;

  select coalesce(sum(points), 0)::integer
  into v_total
  from public.loyalty_ledger
  where btrim(customer_phone) = v_phone;

  insert into public.loyalty_accounts (customer_phone, total_points, updated_at)
  values (v_phone, v_total, now())
  on conflict (customer_phone) do update
  set total_points = excluded.total_points,
      updated_at = now();
end;
$$;

create or replace function public.trg_lock_loyalty_accounts_total_points()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_total integer := 0;
begin
  select coalesce(sum(points), 0)::integer
  into v_total
  from public.loyalty_ledger
  where btrim(customer_phone) = btrim(new.customer_phone);

  new.customer_phone := btrim(new.customer_phone);
  new.total_points := v_total;
  new.updated_at := now();
  return new;
end;
$$;

-- Helper đọc số nguyên không âm từ metadata mà không gây lỗi cast.
create or replace function loyalty_private.jsonb_nonnegative_integer(
  p_value jsonb,
  p_key text
)
returns integer
language plpgsql
immutable
set search_path = pg_catalog
as $$
declare
  v_text text;
begin
  v_text := trim(coalesce(p_value ->> p_key, ''));
  if v_text !~ '^\d+(\.\d+)?$' then
    return null;
  end if;
  return greatest(floor(v_text::numeric)::integer, 0);
exception
  when numeric_value_out_of_range then
    return null;
end;
$$;

-- Snapshot rule cho đơn mới. Chỉ ghi các cột V2, không đổi tổng tiền/status legacy.
create or replace function loyalty_private.snapshot_order_loyalty_rule()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, loyalty_private
as $$
declare
  v_rule public.loyalty_rule_versions%rowtype;
  v_metadata_points integer;
begin
  select * into v_rule
  from public.loyalty_rule_versions
  where status = 'ACTIVE'
    and effective_from <= now()
  order by effective_from desc, version_number desc
  limit 1;

  if not found then
    raise exception 'Chưa có phiên bản quy tắc loyalty đang hoạt động.';
  end if;

  new.loyalty_rule_version_id := v_rule.id;
  new.points_base_amount := greatest(
    coalesce(new.subtotal, 0) - coalesce(new.promo_discount, 0),
    0
  );
  new.expected_earn_points := floor(
    greatest(new.points_base_amount, 0) * v_rule.earn_numerator / v_rule.earn_denominator
  )::integer;
  new.points_discount_amount := coalesce(new.points_discount, 0);

  v_metadata_points := loyalty_private.jsonb_nonnegative_integer(new.metadata, 'pointsSpent');
  new.points_spent := coalesce(new.points_spent, v_metadata_points);

  if new.points_spent is null
    and coalesce(new.points_discount, 0) > 0
    and v_rule.redeem_point_unit = v_rule.redeem_value
  then
    new.points_spent := floor(new.points_discount)::integer;
  end if;

  new.points_spent := coalesce(new.points_spent, 0);
  return new;
end;
$$;

create or replace function loyalty_private.snapshot_partner_order_loyalty_rule()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, loyalty_private
as $$
declare
  v_rule public.loyalty_rule_versions%rowtype;
begin
  select * into v_rule
  from public.loyalty_rule_versions
  where status = 'ACTIVE'
    and effective_from <= now()
  order by effective_from desc, version_number desc
  limit 1;

  if not found then
    raise exception 'Chưa có phiên bản quy tắc loyalty đang hoạt động.';
  end if;

  new.loyalty_rule_version_id := v_rule.id;
  new.points_base_amount := greatest(
    coalesce(new.subtotal, 0) - coalesce(new.discount_amount, 0),
    0
  );
  new.expected_earn_points := floor(
    greatest(new.points_base_amount, 0) * v_rule.earn_numerator / v_rule.earn_denominator
  )::integer;
  new.points_spent := coalesce(new.points_spent, 0);
  new.points_discount_amount := coalesce(new.points_discount_amount, 0);
  return new;
end;
$$;

drop trigger if exists orders_snapshot_loyalty_v2 on public.orders;
create trigger orders_snapshot_loyalty_v2
before insert on public.orders
for each row execute function loyalty_private.snapshot_order_loyalty_rule();

drop trigger if exists partner_orders_snapshot_loyalty_v2 on public.partner_orders;
create trigger partner_orders_snapshot_loyalty_v2
before insert on public.partner_orders
for each row execute function loyalty_private.snapshot_partner_order_loyalty_rule();

-- Backfill snapshot bất biến. Không tạo ledger và không thay đổi số dư.
with active_rule as (
  select *
  from public.loyalty_rule_versions
  where status = 'ACTIVE'
  order by effective_from desc, version_number desc
  limit 1
)
update public.orders o
set
  loyalty_rule_version_id = coalesce(o.loyalty_rule_version_id, r.id),
  points_base_amount = coalesce(
    o.points_base_amount,
    greatest(coalesce(o.subtotal, 0) - coalesce(o.promo_discount, 0), 0)
  ),
  expected_earn_points = coalesce(
    o.expected_earn_points,
    floor(
      greatest(coalesce(o.subtotal, 0) - coalesce(o.promo_discount, 0), 0)
      * r.earn_numerator / r.earn_denominator
    )::integer
  ),
  points_spent = coalesce(
    o.points_spent,
    loyalty_private.jsonb_nonnegative_integer(o.metadata, 'pointsSpent'),
    case
      when coalesce(o.points_discount, 0) > 0
        and r.redeem_point_unit = r.redeem_value
      then floor(o.points_discount)::integer
      else 0
    end
  ),
  points_discount_amount = coalesce(o.points_discount_amount, o.points_discount, 0)
from active_rule r
where o.loyalty_rule_version_id is null
   or o.points_base_amount is null
   or o.expected_earn_points is null
   or o.points_spent is null
   or o.points_discount_amount is null;

with active_rule as (
  select *
  from public.loyalty_rule_versions
  where status = 'ACTIVE'
  order by effective_from desc, version_number desc
  limit 1
)
update public.partner_orders po
set
  loyalty_rule_version_id = coalesce(po.loyalty_rule_version_id, r.id),
  points_base_amount = case
    when coalesce(po.points_base_amount, 0) > 0 then po.points_base_amount
    else greatest(coalesce(po.subtotal, 0) - coalesce(po.discount_amount, 0), 0)
  end,
  expected_earn_points = coalesce(
    po.expected_earn_points,
    floor(
      greatest(
        case
          when coalesce(po.points_base_amount, 0) > 0 then po.points_base_amount
          else coalesce(po.subtotal, 0) - coalesce(po.discount_amount, 0)
        end,
        0
      ) * r.earn_numerator / r.earn_denominator
    )::integer
  ),
  points_spent = coalesce(po.points_spent, 0),
  points_discount_amount = coalesce(po.points_discount_amount, 0)
from active_rule r
where po.loyalty_rule_version_id is null
   or po.expected_earn_points is null
   or po.points_spent is null
   or po.points_discount_amount is null;

-- Backfill định danh ledger chỉ khi khớp chắc chắn và không trùng nghiệp vụ.
with candidates as (
  select
    ll.id,
    row_number() over (
      partition by ll.order_id, ll.entry_type
      order by ll.created_at, ll.id
    ) as occurrence
  from public.loyalty_ledger ll
  join public.orders o on o.id = ll.order_id
  where ll.source_type is null
    and ll.entry_type in ('ORDER_EARN', 'ORDER_SPEND')
    and (
      ll.entry_type = 'ORDER_EARN'
      or (ll.entry_type = 'ORDER_SPEND' and ll.points < 0)
    )
)
update public.loyalty_ledger ll
set
  source_type = 'ORDER',
  source_order_id = ll.order_id,
  action = case ll.entry_type
    when 'ORDER_EARN' then 'SETTLE_EARN'
    else 'SPEND'
  end,
  action_version = 1,
  idempotency_key = 'legacy:' || ll.id,
  rule_version_id = o.loyalty_rule_version_id,
  actor_type = 'LEGACY',
  metadata = coalesce(ll.metadata, '{}'::jsonb)
    || jsonb_build_object('loyaltyV2Backfilled', true)
from candidates c
join public.orders o on o.id = (
  select x.order_id from public.loyalty_ledger x where x.id = c.id
)
where ll.id = c.id
  and c.occurrence = 1;

with candidates as (
  select
    ll.id,
    row_number() over (
      partition by ll.partner_order_id
      order by ll.created_at, ll.id
    ) as occurrence
  from public.loyalty_ledger ll
  join public.partner_orders po on po.id = ll.partner_order_id
  where ll.source_type is null
    and ll.entry_type = 'PARTNER_ORDER_EARN'
)
update public.loyalty_ledger ll
set
  source_type = 'PARTNER_ORDER',
  source_order_id = ll.partner_order_id::text,
  action = 'CLAIM_PARTNER_EARN',
  action_version = 1,
  idempotency_key = 'legacy:' || ll.id,
  rule_version_id = po.loyalty_rule_version_id,
  actor_type = 'LEGACY',
  metadata = coalesce(ll.metadata, '{}'::jsonb)
    || jsonb_build_object('loyaltyV2Backfilled', true)
from candidates c
join public.partner_orders po on po.id = (
  select x.partner_order_id from public.loyalty_ledger x where x.id = c.id
)
where ll.id = c.id
  and c.occurrence = 1;

-- Actor helper. Không dựa vào user_metadata của JWT.
create or replace function loyalty_private.current_actor(
  out actor_type text,
  out actor_id uuid,
  out actor_phone text,
  out actor_role text
)
returns record
language plpgsql
stable
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_jwt_role text := coalesce(auth.jwt() ->> 'role', '');
begin
  if v_jwt_role = 'service_role' then
    actor_type := 'SERVICE';
    actor_id := null;
    actor_phone := '';
    actor_role := 'service_role';
    return;
  end if;

  if v_uid is null then
    actor_type := 'ANONYMOUS';
    actor_id := null;
    actor_phone := '';
    actor_role := '';
    return;
  end if;

  select
    'PROFILE',
    p.id,
    public.normalize_vietnam_phone(p.phone),
    lower(coalesce(p.role, ''))
  into actor_type, actor_id, actor_phone, actor_role
  from public.profiles p
  where p.auth_user_id = v_uid
    and lower(coalesce(p.status, '')) = 'active'
  limit 1;

  if not found then
    actor_type := 'AUTHENTICATED';
    actor_id := null;
    actor_phone := '';
    actor_role := '';
  end if;
end;
$$;

create or replace function loyalty_private.process_order_loyalty_internal(
  p_source_type text,
  p_source_order_id text,
  p_action text,
  p_idempotency_key text
)
returns table (
  ok boolean,
  applied boolean,
  event_id text,
  action text,
  points_delta integer,
  balance_before integer,
  balance_after integer,
  message text
)
language plpgsql
security definer
set search_path = pg_catalog, public, loyalty_private, auth
as $$
declare
  v_source_type text := upper(trim(coalesce(p_source_type, '')));
  v_source_order_id text := trim(coalesce(p_source_order_id, ''));
  v_action text := upper(trim(coalesce(p_action, '')));
  v_idempotency_key text := trim(coalesce(p_idempotency_key, ''));
  v_phone text;
  v_order_status text;
  v_order_code text;
  v_rule_version_id uuid;
  v_points_base numeric := 0;
  v_expected_earn integer := 0;
  v_points_spent integer := 0;
  v_partner_order_id uuid;
  v_actor_type text;
  v_actor_id uuid;
  v_actor_phone text;
  v_actor_role text;
  v_event_id text;
  v_delta integer;
  v_balance_before integer;
  v_balance_after integer;
  v_original public.loyalty_ledger%rowtype;
  v_existing public.loyalty_ledger%rowtype;
  v_inserted_id text;
  v_profile_id uuid;
begin
  if v_source_type not in ('ORDER', 'PARTNER_ORDER') then
    raise exception 'Nguồn đơn loyalty không hợp lệ.';
  end if;
  if v_source_order_id = '' then
    raise exception 'Thiếu định danh đơn hàng.';
  end if;
  if v_action not in ('SPEND', 'SETTLE_EARN', 'REVERSE_SPEND', 'REVERSE_EARN', 'CLAIM_PARTNER_EARN') then
    raise exception 'Hành động loyalty không hợp lệ.';
  end if;
  if v_idempotency_key = '' or length(v_idempotency_key) > 200 then
    raise exception 'Idempotency key không hợp lệ.';
  end if;

  if v_source_type = 'ORDER' then
    select
      public.normalize_vietnam_phone(o.customer_phone),
      lower(trim(coalesce(o.status, ''))),
      o.order_code,
      o.loyalty_rule_version_id,
      coalesce(o.points_base_amount, 0),
      coalesce(o.expected_earn_points, 0),
      coalesce(o.points_spent, 0)
    into
      v_phone, v_order_status, v_order_code, v_rule_version_id,
      v_points_base, v_expected_earn, v_points_spent
    from public.orders o
    where o.id = v_source_order_id
    for update;

    if not found then
      raise exception 'Không tìm thấy đơn trong orders.';
    end if;
  else
    begin
      v_partner_order_id := v_source_order_id::uuid;
    exception when invalid_text_representation then
      raise exception 'partner_order_id không đúng định dạng UUID.';
    end;

    select
      public.normalize_vietnam_phone(
        coalesce(nullif(po.customer_phone_key, ''), po.customer_phone)
      ),
      lower(trim(coalesce(po.order_status, ''))),
      po.order_code,
      po.loyalty_rule_version_id,
      coalesce(po.points_base_amount, 0),
      coalesce(po.expected_earn_points, 0),
      coalesce(po.points_spent, 0)
    into
      v_phone, v_order_status, v_order_code, v_rule_version_id,
      v_points_base, v_expected_earn, v_points_spent
    from public.partner_orders po
    where po.id = v_partner_order_id
    for update;

    if not found then
      raise exception 'Không tìm thấy đơn trong partner_orders.';
    end if;
  end if;

  if v_phone = '' then
    raise exception 'Đơn không có số điện thoại hợp lệ để xử lý loyalty.';
  end if;

  select *
  into v_actor_type, v_actor_id, v_actor_phone, v_actor_role
  from loyalty_private.current_actor();

  if v_actor_role = 'service_role' then
    null;
  elsif v_actor_role in ('admin', 'staff', 'kitchen') then
    null;
  elsif v_action = 'CLAIM_PARTNER_EARN'
    and v_source_type = 'PARTNER_ORDER'
    and v_actor_role = 'customer'
    and v_actor_phone = v_phone
  then
    null;
  else
    raise exception 'Tài khoản hiện tại không được phép thực hiện hành động loyalty này.';
  end if;

  if v_action = 'SPEND' then
    if v_source_type <> 'ORDER' then
      raise exception 'Chỉ đơn trong orders mới được sử dụng điểm.';
    end if;
    if v_order_status in ('cancelled', 'canceled', 'cancel', 'refunded') then
      raise exception 'Không thể trừ điểm cho đơn đã hủy hoặc hoàn tiền.';
    end if;
    if v_points_spent <= 0 then
      raise exception 'Đơn không có snapshot points_spent hợp lệ.';
    end if;
    v_delta := -v_points_spent;
  elsif v_action = 'SETTLE_EARN' then
    if v_source_type <> 'ORDER' then
      raise exception 'Đơn đối tác phải dùng CLAIM_PARTNER_EARN.';
    end if;
    if v_order_status not in ('completed', 'done', 'hoan_tat', 'hoan tat') then
      raise exception 'Chỉ cộng điểm khi đơn đã hoàn tất.';
    end if;
    if v_expected_earn <= 0 then
      raise exception 'Đơn không có expected_earn_points hợp lệ.';
    end if;
    v_delta := v_expected_earn;
  elsif v_action = 'CLAIM_PARTNER_EARN' then
    if v_source_type <> 'PARTNER_ORDER' then
      raise exception 'CLAIM_PARTNER_EARN chỉ áp dụng cho partner_orders.';
    end if;
    if v_order_status not in ('completed', 'done', 'hoan_tat', 'hoan tat') then
      raise exception 'Đơn đối tác chưa hoàn tất nên chưa thể nhận điểm.';
    end if;
    if v_expected_earn <= 0 then
      raise exception 'Đơn đối tác không có expected_earn_points hợp lệ.';
    end if;
    v_delta := v_expected_earn;
  elsif v_action = 'REVERSE_SPEND' then
    if v_order_status not in ('cancelled', 'canceled', 'cancel', 'refunded') then
      raise exception 'Chỉ hoàn điểm đã dùng khi đơn đã hủy hoặc hoàn tiền.';
    end if;
    select * into v_original
    from public.loyalty_ledger ll
    where ll.source_type = v_source_type
      and ll.source_order_id = v_source_order_id
      and ll.action = 'SPEND'
      and ll.action_version = 1
    limit 1
    for update;
    if not found then
      raise exception 'Không tìm thấy giao dịch SPEND gốc.';
    end if;
    v_delta := -v_original.points;
  elsif v_action = 'REVERSE_EARN' then
    if v_order_status not in ('cancelled', 'canceled', 'cancel', 'refunded') then
      raise exception 'Chỉ thu hồi điểm khi đơn đã hủy hoặc hoàn tiền.';
    end if;
    select * into v_original
    from public.loyalty_ledger ll
    where ll.source_type = v_source_type
      and ll.source_order_id = v_source_order_id
      and ll.action in ('SETTLE_EARN', 'CLAIM_PARTNER_EARN')
      and ll.action_version = 1
    order by case when ll.action = 'SETTLE_EARN' then 0 else 1 end
    limit 1
    for update;
    if not found then
      raise exception 'Không tìm thấy giao dịch cộng điểm gốc.';
    end if;
    v_delta := -v_original.points;
  end if;

  -- Tạo account trước rồi khóa theo khách để tuần tự hóa mọi biến động số dư.
  insert into public.loyalty_accounts (customer_phone, total_points, metadata)
  values (v_phone, 0, jsonb_build_object('source', 'loyalty_v2'))
  on conflict (customer_phone) do nothing;

  select coalesce(la.total_points, 0)::integer
  into v_balance_before
  from public.loyalty_accounts la
  where la.customer_phone = v_phone
  for update;

  select * into v_existing
  from public.loyalty_ledger ll
  where ll.source_type = v_source_type
    and ll.source_order_id = v_source_order_id
    and ll.action = v_action
    and ll.action_version = 1
  limit 1;

  if found then
    return query select
      true, false, v_existing.id, v_action, v_existing.points,
      v_balance_before, v_balance_before,
      'Sự kiện đã được xử lý trước đó.';
    return;
  end if;

  if v_balance_before + v_delta < 0 and v_action <> 'REVERSE_EARN' then
    raise exception 'Khách không đủ điểm. Hiện có %, cần %.',
      v_balance_before, abs(v_delta);
  end if;

  v_event_id := 'loyalty-v2-' || gen_random_uuid()::text;

  insert into public.loyalty_ledger (
    id,
    customer_phone,
    entry_type,
    order_id,
    points,
    amount,
    title,
    note,
    metadata,
    partner_order_id,
    partner_order_code,
    source,
    source_type,
    source_order_id,
    action,
    action_version,
    idempotency_key,
    rule_version_id,
    reversal_of_ledger_id,
    actor_type,
    actor_id,
    created_at
  ) values (
    v_event_id,
    v_phone,
    case v_action
      when 'SPEND' then 'ORDER_SPEND'
      when 'SETTLE_EARN' then 'ORDER_EARN'
      when 'REVERSE_SPEND' then 'ORDER_SPEND_REVERSED'
      when 'REVERSE_EARN' then 'ORDER_EARN_REVERSED'
      else 'PARTNER_ORDER_EARN'
    end,
    case when v_source_type = 'ORDER' then v_source_order_id else null end,
    v_delta,
    v_points_base,
    case v_action
      when 'SPEND' then 'Sử dụng điểm cho đơn hàng'
      when 'SETTLE_EARN' then 'Cộng điểm đơn hoàn tất'
      when 'REVERSE_SPEND' then 'Hoàn điểm đơn hủy'
      when 'REVERSE_EARN' then 'Thu hồi điểm đơn hủy'
      else 'Cộng điểm đơn đối tác'
    end,
    'Đơn ' || coalesce(nullif(v_order_code, ''), v_source_order_id),
    jsonb_build_object(
      'source', 'loyalty_v2',
      'sourceType', v_source_type,
      'sourceOrderId', v_source_order_id,
      'action', v_action,
      'pointsBaseAmount', v_points_base
    ),
    case when v_source_type = 'PARTNER_ORDER' then v_partner_order_id else null end,
    case when v_source_type = 'PARTNER_ORDER' then v_order_code else null end,
    case when v_source_type = 'PARTNER_ORDER' then 'partner' else 'order' end,
    v_source_type,
    v_source_order_id,
    v_action,
    1,
    v_idempotency_key,
    v_rule_version_id,
    case when v_action in ('REVERSE_SPEND', 'REVERSE_EARN') then v_original.id else null end,
    v_actor_type,
    v_actor_id,
    now()
  )
  on conflict do nothing
  returning id into v_inserted_id;

  if v_inserted_id is null then
    select * into v_existing
    from public.loyalty_ledger ll
    where ll.source_type = v_source_type
      and ll.source_order_id = v_source_order_id
      and ll.action = v_action
      and ll.action_version = 1
    order by ll.created_at
    limit 1;

    if not found then
      if exists (
        select 1
        from public.loyalty_ledger ll
        where ll.idempotency_key = v_idempotency_key
      ) then
        raise exception 'Idempotency key đã được dùng cho một sự kiện khác.';
      end if;
      raise exception 'Không thể tạo sự kiện loyalty do xung đột dữ liệu.';
    end if;

    select coalesce(la.total_points, 0)::integer
    into v_balance_after
    from public.loyalty_accounts la
    where la.customer_phone = v_phone;

    return query select
      true, false, v_existing.id, v_action, coalesce(v_existing.points, 0),
      v_balance_before, v_balance_after,
      'Sự kiện đã được xử lý trước đó.';
    return;
  end if;

  if v_action = 'CLAIM_PARTNER_EARN' then
    select p.id into v_profile_id
    from public.profiles p
    where public.normalize_vietnam_phone(p.phone) = v_phone
    order by (p.auth_user_id is not null) desc, p.created_at
    limit 1;

    update public.partner_orders
    set
      point_status = 'claimed',
      claimed_by_profile_id = coalesce(v_profile_id, claimed_by_profile_id),
      claimed_customer_phone = v_phone,
      claimed_at = coalesce(claimed_at, now())
    where id = v_partner_order_id;
  end if;

  select coalesce(la.total_points, 0)::integer
  into v_balance_after
  from public.loyalty_accounts la
  where la.customer_phone = v_phone;

  return query select
    true, true, v_event_id, v_action, v_delta,
    v_balance_before, v_balance_after,
    'Xử lý loyalty thành công.';
end;
$$;

-- Public façade: không nhận phone, amount hoặc points.
create or replace function public.process_order_loyalty(
  p_source_type text,
  p_source_order_id text,
  p_action text,
  p_idempotency_key text
)
returns table (
  ok boolean,
  applied boolean,
  event_id text,
  action text,
  points_delta integer,
  balance_before integer,
  balance_after integer,
  message text
)
language sql
security invoker
set search_path = pg_catalog, public, loyalty_private
as $$
  select *
  from loyalty_private.process_order_loyalty_internal(
    p_source_type,
    p_source_order_id,
    p_action,
    p_idempotency_key
  );
$$;

-- Điểm danh: daily và milestone được quyết định tại database trong cùng transaction.
create or replace function loyalty_private.checkin_internal(
  p_idempotency_key text
)
returns table (
  ok boolean,
  applied boolean,
  event_id text,
  action text,
  points_delta integer,
  balance_before integer,
  balance_after integer,
  checkin_streak integer,
  message text
)
language plpgsql
security definer
set search_path = pg_catalog, public, loyalty_private, auth
as $$
declare
  v_actor_type text;
  v_actor_id uuid;
  v_phone text;
  v_actor_role text;
  v_rule public.loyalty_rule_versions%rowtype;
  v_business_date date := timezone('Asia/Ho_Chi_Minh', now())::date;
  v_last_date date;
  v_streak integer;
  v_daily_points integer;
  v_milestone_points integer := 0;
  v_balance_before integer;
  v_balance_after integer;
  v_event_id text;
  v_milestone_id text;
  v_inserted_id text;
  v_idempotency_key text := trim(coalesce(p_idempotency_key, ''));
  v_existing public.loyalty_ledger%rowtype;
begin
  if v_idempotency_key = '' or length(v_idempotency_key) > 200 then
    raise exception 'Idempotency key không hợp lệ.';
  end if;

  select *
  into v_actor_type, v_actor_id, v_phone, v_actor_role
  from loyalty_private.current_actor();

  if v_actor_role <> 'customer' or v_phone = '' then
    raise exception 'Chỉ khách hàng đã xác thực mới được điểm danh.';
  end if;

  select * into v_rule
  from public.loyalty_rule_versions
  where status = 'ACTIVE'
    and effective_from <= now()
  order by effective_from desc, version_number desc
  limit 1;

  if not found or v_rule.checkin_daily_points <= 0 then
    raise exception 'Tính năng điểm danh hiện chưa được bật.';
  end if;

  insert into public.loyalty_accounts (customer_phone, total_points, metadata)
  values (v_phone, 0, jsonb_build_object('source', 'loyalty_v2_checkin'))
  on conflict (customer_phone) do nothing;

  select
    coalesce(la.total_points, 0)::integer,
    case
      when coalesce(la.last_checkin_date, '') ~ '^\d{4}-\d{2}-\d{2}$'
      then la.last_checkin_date::date
      else null
    end,
    coalesce(la.checkin_streak, 0)
  into v_balance_before, v_last_date, v_streak
  from public.loyalty_accounts la
  where la.customer_phone = v_phone
  for update;

  select * into v_existing
  from public.loyalty_ledger ll
  where ll.source_type = 'CUSTOMER_DAY'
    and ll.source_order_id = v_phone || ':' || v_business_date::text
    and ll.action = 'CHECKIN'
    and ll.action_version = 1
  limit 1;

  if found then
    return query select
      true, false, v_existing.id, 'CHECKIN', v_existing.points,
      v_balance_before, v_balance_before, v_streak,
      'Hôm nay khách đã điểm danh.';
    return;
  end if;

  if v_last_date = v_business_date - 1 then
    v_streak := v_streak + 1;
  else
    v_streak := 1;
  end if;

  v_daily_points := v_rule.checkin_daily_points;
  if coalesce(v_rule.streak_rewards ->> v_streak::text, '') ~ '^\d+$' then
    v_milestone_points := greatest((v_rule.streak_rewards ->> v_streak::text)::integer, 0);
  end if;

  v_event_id := 'loyalty-v2-checkin-' || gen_random_uuid()::text;

  insert into public.loyalty_ledger (
    id, customer_phone, entry_type, order_id, points, amount, title, note,
    metadata, source, source_type, source_order_id, action, action_version,
    idempotency_key, rule_version_id, actor_type, actor_id, created_at
  ) values (
    v_event_id,
    v_phone,
    'CHECKIN_V2',
    null,
    v_daily_points,
    0,
    'Điểm danh hằng ngày',
    'Ngày ' || to_char(v_business_date, 'DD/MM/YYYY'),
    jsonb_build_object(
      'source', 'loyalty_v2',
      'businessDate', v_business_date,
      'streak', v_streak
    ),
    'checkin',
    'CUSTOMER_DAY',
    v_phone || ':' || v_business_date::text,
    'CHECKIN',
    1,
    v_idempotency_key,
    v_rule.id,
    v_actor_type,
    v_actor_id,
    now()
  )
  on conflict do nothing
  returning id into v_inserted_id;

  if v_inserted_id is null then
    select * into v_existing
    from public.loyalty_ledger ll
    where ll.source_type = 'CUSTOMER_DAY'
      and ll.source_order_id = v_phone || ':' || v_business_date::text
      and ll.action = 'CHECKIN'
      and ll.action_version = 1
    limit 1;

    if not found then
      if exists (
        select 1
        from public.loyalty_ledger ll
        where ll.idempotency_key = v_idempotency_key
      ) then
        raise exception 'Idempotency key đã được dùng cho một sự kiện khác.';
      end if;
      raise exception 'Không thể tạo sự kiện điểm danh do xung đột dữ liệu.';
    end if;

    select coalesce(total_points, 0)::integer
    into v_balance_after
    from public.loyalty_accounts
    where customer_phone = v_phone;

    return query select
      true, false, v_existing.id, 'CHECKIN', v_existing.points,
      v_balance_before, v_balance_after, v_streak,
      'Hôm nay khách đã điểm danh.';
    return;
  end if;

  if v_milestone_points > 0 then
    v_milestone_id := 'loyalty-v2-milestone-' || gen_random_uuid()::text;
    insert into public.loyalty_ledger (
      id, customer_phone, entry_type, order_id, points, amount, title, note,
      metadata, source, source_type, source_order_id, action, action_version,
      idempotency_key, rule_version_id, actor_type, actor_id, created_at
    ) values (
      v_milestone_id,
      v_phone,
      'MILESTONE',
      null,
      v_milestone_points,
      0,
      'Thưởng chuỗi điểm danh',
      'Mốc ' || v_streak::text || ' ngày liên tiếp',
      jsonb_build_object(
        'source', 'loyalty_v2',
        'businessDate', v_business_date,
        'streak', v_streak
      ),
      'checkin',
      'CUSTOMER_STREAK',
      v_phone || ':' || v_business_date::text || ':' || v_streak::text,
      'MILESTONE',
      1,
      v_idempotency_key || ':milestone:' || v_streak::text,
      v_rule.id,
      v_actor_type,
      v_actor_id,
      now()
    )
    on conflict do nothing;
  end if;

  update public.loyalty_accounts
  set
    checkin_streak = v_streak,
    last_checkin_date = v_business_date::text,
    updated_at = now()
  where customer_phone = v_phone;

  select coalesce(total_points, 0)::integer
  into v_balance_after
  from public.loyalty_accounts
  where customer_phone = v_phone;

  return query select
    true, true, v_event_id, 'CHECKIN', v_daily_points + v_milestone_points,
    v_balance_before, v_balance_after, v_streak,
    case
      when v_milestone_points > 0
      then 'Điểm danh và nhận thưởng mốc thành công.'
      else 'Điểm danh thành công.'
    end;
end;
$$;

create or replace function public.process_loyalty_checkin(
  p_idempotency_key text
)
returns table (
  ok boolean,
  applied boolean,
  event_id text,
  action text,
  points_delta integer,
  balance_before integer,
  balance_after integer,
  checkin_streak integer,
  message text
)
language sql
security invoker
set search_path = pg_catalog, public, loyalty_private
as $$
  select * from loyalty_private.checkin_internal(p_idempotency_key);
$$;

-- Admin adjustment luôn tạo ledger, không sửa thẳng total_points.
create or replace function loyalty_private.admin_adjust_internal(
  p_customer_phone text,
  p_points integer,
  p_reason text,
  p_idempotency_key text
)
returns table (
  ok boolean,
  applied boolean,
  event_id text,
  action text,
  points_delta integer,
  balance_before integer,
  balance_after integer,
  message text
)
language plpgsql
security definer
set search_path = pg_catalog, public, loyalty_private, auth
as $$
declare
  v_actor_type text;
  v_actor_id uuid;
  v_actor_phone text;
  v_actor_role text;
  v_phone text := public.normalize_vietnam_phone(p_customer_phone);
  v_reason text := trim(coalesce(p_reason, ''));
  v_key text := trim(coalesce(p_idempotency_key, ''));
  v_before integer;
  v_after integer;
  v_event_id text;
  v_existing public.loyalty_ledger%rowtype;
begin
  select *
  into v_actor_type, v_actor_id, v_actor_phone, v_actor_role
  from loyalty_private.current_actor();

  if v_actor_role <> 'admin' then
    raise exception 'Chỉ admin được điều chỉnh điểm.';
  end if;
  if v_phone = '' then
    raise exception 'Số điện thoại khách không hợp lệ.';
  end if;
  if coalesce(p_points, 0) = 0 then
    raise exception 'Số điểm điều chỉnh phải khác 0.';
  end if;
  if length(v_reason) < 3 then
    raise exception 'Bắt buộc nhập lý do điều chỉnh.';
  end if;
  if v_key = '' or length(v_key) > 200 then
    raise exception 'Idempotency key không hợp lệ.';
  end if;

  insert into public.profiles (phone, registered, role, status, metadata)
  values (v_phone, false, 'customer', 'active', jsonb_build_object('source', 'loyalty_v2_admin'))
  on conflict (phone) do nothing;

  insert into public.loyalty_accounts (customer_phone, total_points, metadata)
  values (v_phone, 0, jsonb_build_object('source', 'loyalty_v2_admin'))
  on conflict (customer_phone) do nothing;

  select coalesce(total_points, 0)::integer
  into v_before
  from public.loyalty_accounts
  where customer_phone = v_phone
  for update;

  select * into v_existing
  from public.loyalty_ledger
  where idempotency_key = v_key
  limit 1;

  if found then
    return query select
      true, false, v_existing.id, 'ADMIN_ADJUST', v_existing.points,
      v_before, v_before, 'Yêu cầu đã được xử lý trước đó.';
    return;
  end if;

  if v_before + p_points < 0 then
    raise exception 'Điều chỉnh làm số dư âm. Hiện có %, thay đổi %.', v_before, p_points;
  end if;

  v_event_id := 'loyalty-v2-admin-' || gen_random_uuid()::text;
  insert into public.loyalty_ledger (
    id, customer_phone, entry_type, order_id, points, amount, title, note,
    metadata, source, source_type, source_order_id, action, action_version,
    idempotency_key, actor_type, actor_id, created_at
  ) values (
    v_event_id,
    v_phone,
    'ADMIN_ADJUST',
    null,
    p_points,
    0,
    'Admin điều chỉnh điểm',
    v_reason,
    jsonb_build_object('source', 'loyalty_v2', 'reason', v_reason),
    'admin',
    'ADMIN',
    v_key,
    'ADMIN_ADJUST',
    1,
    v_key,
    v_actor_type,
    v_actor_id,
    now()
  );

  select coalesce(total_points, 0)::integer
  into v_after
  from public.loyalty_accounts
  where customer_phone = v_phone;

  return query select
    true, true, v_event_id, 'ADMIN_ADJUST', p_points,
    v_before, v_after, 'Điều chỉnh điểm thành công.';
end;
$$;

create or replace function public.admin_adjust_loyalty_points(
  p_customer_phone text,
  p_points integer,
  p_reason text,
  p_idempotency_key text
)
returns table (
  ok boolean,
  applied boolean,
  event_id text,
  action text,
  points_delta integer,
  balance_before integer,
  balance_after integer,
  message text
)
language sql
security invoker
set search_path = pg_catalog, public, loyalty_private
as $$
  select * from loyalty_private.admin_adjust_internal(
    p_customer_phone,
    p_points,
    p_reason,
    p_idempotency_key
  );
$$;

-- Kích hoạt phiên bản rule mới. Chỉ admin, không tính lại đơn cũ.
create or replace function loyalty_private.activate_rule_internal(
  p_earn_numerator bigint,
  p_earn_denominator bigint,
  p_redeem_point_unit bigint,
  p_redeem_value bigint,
  p_checkin_daily_points integer,
  p_streak_rewards jsonb,
  p_idempotency_key text
)
returns table (
  ok boolean,
  rule_version_id uuid,
  version_number bigint,
  message text
)
language plpgsql
security definer
set search_path = pg_catalog, public, loyalty_private, auth
as $$
declare
  v_actor_type text;
  v_actor_id uuid;
  v_actor_phone text;
  v_actor_role text;
  v_key text := trim(coalesce(p_idempotency_key, ''));
  v_existing public.loyalty_rule_versions%rowtype;
  v_new public.loyalty_rule_versions%rowtype;
  v_config jsonb;
begin
  select *
  into v_actor_type, v_actor_id, v_actor_phone, v_actor_role
  from loyalty_private.current_actor();

  if v_actor_role <> 'admin' then
    raise exception 'Chỉ admin được thay đổi quy tắc loyalty.';
  end if;
  if coalesce(p_earn_numerator, 0) <= 0 or coalesce(p_earn_denominator, 0) <= 0 then
    raise exception 'Tỷ lệ tích điểm phải lớn hơn 0.';
  end if;
  if coalesce(p_redeem_point_unit, 0) <= 0 or coalesce(p_redeem_value, 0) <= 0 then
    raise exception 'Tỷ lệ đổi điểm phải lớn hơn 0.';
  end if;
  if coalesce(p_checkin_daily_points, 0) < 0 then
    raise exception 'Điểm danh hằng ngày không được âm.';
  end if;
  if v_key = '' or length(v_key) > 200 then
    raise exception 'Idempotency key không hợp lệ.';
  end if;

  select * into v_existing
  from public.loyalty_rule_versions
  where source_config ->> 'idempotencyKey' = v_key
  order by created_at
  limit 1;

  if found then
    return query select true, v_existing.id, v_existing.version_number,
      'Phiên bản quy tắc đã được tạo trước đó.';
    return;
  end if;

  update public.loyalty_rule_versions
  set status = 'RETIRED', retired_at = now()
  where status = 'ACTIVE';

  v_config := jsonb_build_object(
    'enabled', true,
    'currencyPerPoint', p_earn_denominator,
    'pointPerUnit', p_earn_numerator,
    'redeemPointUnit', p_redeem_point_unit,
    'redeemValue', p_redeem_value,
    'checkinDailyPoints', p_checkin_daily_points,
    'streakRewards', coalesce(p_streak_rewards, '{}'::jsonb),
    'idempotencyKey', v_key,
    'source', 'loyalty_v2'
  );

  insert into public.loyalty_rule_versions (
    status,
    effective_from,
    earn_numerator,
    earn_denominator,
    redeem_point_unit,
    redeem_value,
    checkin_daily_points,
    streak_rewards,
    source_config,
    created_by
  ) values (
    'ACTIVE',
    now(),
    p_earn_numerator,
    p_earn_denominator,
    p_redeem_point_unit,
    p_redeem_value,
    p_checkin_daily_points,
    coalesce(p_streak_rewards, '{}'::jsonb),
    v_config,
    auth.uid()
  )
  returning * into v_new;

  insert into public.app_configs (id, value, updated_at)
  values ('ghr_loyalty', v_config, now())
  on conflict (id) do update
  set
    value = coalesce(public.app_configs.value, '{}'::jsonb) || excluded.value,
    updated_at = now();

  return query select true, v_new.id, v_new.version_number,
    'Đã kích hoạt quy tắc mới; đơn cũ giữ nguyên snapshot.';
end;
$$;

create or replace function public.activate_loyalty_rule_version(
  p_earn_numerator bigint,
  p_earn_denominator bigint,
  p_redeem_point_unit bigint,
  p_redeem_value bigint,
  p_checkin_daily_points integer,
  p_streak_rewards jsonb,
  p_idempotency_key text
)
returns table (
  ok boolean,
  rule_version_id uuid,
  version_number bigint,
  message text
)
language sql
security invoker
set search_path = pg_catalog, public, loyalty_private
as $$
  select * from loyalty_private.activate_rule_internal(
    p_earn_numerator,
    p_earn_denominator,
    p_redeem_point_unit,
    p_redeem_value,
    p_checkin_daily_points,
    p_streak_rewards,
    p_idempotency_key
  );
$$;

-- Quyền tối thiểu cho façade. Schema private không nằm trong Data API exposed schemas.
grant usage on schema loyalty_private to authenticated, service_role;

revoke all on function loyalty_private.jsonb_nonnegative_integer(jsonb, text)
from public, anon, authenticated;
revoke all on function loyalty_private.snapshot_order_loyalty_rule()
from public, anon, authenticated;
revoke all on function loyalty_private.snapshot_partner_order_loyalty_rule()
from public, anon, authenticated;
revoke all on function loyalty_private.current_actor()
from public, anon, authenticated;

revoke all on function loyalty_private.process_order_loyalty_internal(text, text, text, text)
from public, anon;
grant execute on function loyalty_private.process_order_loyalty_internal(text, text, text, text)
to authenticated, service_role;

revoke all on function loyalty_private.checkin_internal(text)
from public, anon;
grant execute on function loyalty_private.checkin_internal(text)
to authenticated, service_role;

revoke all on function loyalty_private.admin_adjust_internal(text, integer, text, text)
from public, anon;
grant execute on function loyalty_private.admin_adjust_internal(text, integer, text, text)
to authenticated, service_role;

revoke all on function loyalty_private.activate_rule_internal(bigint, bigint, bigint, bigint, integer, jsonb, text)
from public, anon;
grant execute on function loyalty_private.activate_rule_internal(bigint, bigint, bigint, bigint, integer, jsonb, text)
to authenticated, service_role;

revoke execute on function public.process_order_loyalty(text, text, text, text)
from public, anon;
grant execute on function public.process_order_loyalty(text, text, text, text)
to authenticated, service_role;

revoke execute on function public.process_loyalty_checkin(text)
from public, anon;
grant execute on function public.process_loyalty_checkin(text)
to authenticated;

revoke execute on function public.admin_adjust_loyalty_points(text, integer, text, text)
from public, anon;
grant execute on function public.admin_adjust_loyalty_points(text, integer, text, text)
to authenticated;

revoke execute on function public.activate_loyalty_rule_version(bigint, bigint, bigint, bigint, integer, jsonb, text)
from public, anon;
grant execute on function public.activate_loyalty_rule_version(bigint, bigint, bigint, bigint, integer, jsonb, text)
to authenticated;

-- Legacy RPC/RLS chưa bị thu hồi trong migration này để tránh phá runtime trước cutover.
-- Script cutover độc lập nằm tại docs/supabase-sql/loyalty-v2-phase-2-security-cutover.sql.

alter table public.orders validate constraint orders_loyalty_rule_version_fk;
alter table public.partner_orders validate constraint partner_orders_loyalty_rule_version_fk;
alter table public.loyalty_ledger validate constraint loyalty_ledger_rule_version_fk;
alter table public.loyalty_ledger validate constraint loyalty_ledger_reversal_fk;
alter table public.loyalty_ledger validate constraint loyalty_ledger_v2_source_check;
alter table public.loyalty_ledger validate constraint loyalty_ledger_v2_action_check;
alter table public.loyalty_ledger validate constraint loyalty_ledger_v2_identity_check;
alter table public.loyalty_ledger validate constraint loyalty_ledger_v2_sign_check;

comment on table public.loyalty_rule_versions is
  'Phiên bản quy tắc Loyalty V2 bất biến; thay rule bằng cách tạo version mới.';
comment on function public.process_order_loyalty(text, text, text, text) is
  'Façade Loyalty V2 cho ORDER/PARTNER_ORDER; database tự đọc phone, status, amount và points.';
comment on function public.process_loyalty_checkin(text) is
  'Điểm danh và milestone atomic, chống trùng theo khách và ngày kinh doanh.';
comment on function public.admin_adjust_loyalty_points(text, integer, text, text) is
  'Điều chỉnh điểm bởi admin qua ledger; không sửa trực tiếp total_points.';

-- Migration phải tự dừng nếu nền tảng không đạt các bất biến quan trọng.
do $$
declare
  v_count bigint;
  v_account_total bigint;
  v_ledger_total bigint;
begin
  select count(*) into v_count
  from public.loyalty_rule_versions
  where status = 'ACTIVE';
  if v_count <> 1 then
    raise exception 'Loyalty V2 cần đúng một rule ACTIVE, hiện có %.', v_count;
  end if;

  select count(*) into v_count
  from public.orders
  where loyalty_rule_version_id is null
     or points_base_amount is null
     or expected_earn_points is null
     or points_spent is null
     or points_discount_amount is null;
  if v_count <> 0 then
    raise exception 'Còn % orders thiếu snapshot Loyalty V2.', v_count;
  end if;

  select count(*) into v_count
  from public.partner_orders
  where loyalty_rule_version_id is null
     or expected_earn_points is null
     or points_spent is null
     or points_discount_amount is null;
  if v_count <> 0 then
    raise exception 'Còn % partner_orders thiếu snapshot Loyalty V2.', v_count;
  end if;

  select coalesce(sum(total_points), 0)::bigint
  into v_account_total
  from public.loyalty_accounts;

  select coalesce(sum(points), 0)::bigint
  into v_ledger_total
  from public.loyalty_ledger;

  if v_account_total <> v_ledger_total then
    raise exception 'Tổng account % không khớp ledger %.', v_account_total, v_ledger_total;
  end if;

  if to_regprocedure('public.process_order_loyalty(text,text,text,text)') is null
    or to_regprocedure('public.process_loyalty_checkin(text)') is null
    or to_regprocedure('public.admin_adjust_loyalty_points(text,integer,text,text)') is null
    or to_regprocedure('public.activate_loyalty_rule_version(bigint,bigint,bigint,bigint,integer,jsonb,text)') is null
  then
    raise exception 'Thiếu một hoặc nhiều RPC Loyalty V2.';
  end if;

  if has_function_privilege(
    'anon',
    'public.process_order_loyalty(text,text,text,text)',
    'EXECUTE'
  ) then
    raise exception 'anon không được có quyền gọi process_order_loyalty.';
  end if;
end;
$$;

notify pgrst, 'reload schema';

-- Dry-run trên linked database đã đạt; migration chính thức commit toàn bộ hoặc rollback khi có lỗi.
commit;
